"""3rd migration

Revision ID: 04638bcf5fe6
Revises: 5eb652fe2078
Create Date: 2019-04-28 14:17:42.603365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04638bcf5fe6'
down_revision = '5eb652fe2078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
